Description: >  
  'Capstone proyect. Create Cluster'

Parameter:
  EnvironmentName:
    Description: Some text here
    Type: String
    Default: Prod


Resources:

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub ${EnvironmentName}-Cluster
      Version: "1.20"
      RoleArn: "arn:aws:iam::246528985509:role/UdaEKSClusterAccess"
      ResourcesVpcConfig:
        SecurityGroupIds:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-SecurityGroups"
        SubnetIds:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-SubnetIds"
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
        PublicAccessCidrs: [ "1.1.1.2/32" ]
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
      Tags:
        - Key: "Name"
          Value: !Sub ${EnvironmentName}-Cluster
