version: 2.1

aws_docker_image: &aws_docker_image
  docker:
    - image: amazon/aws-cli

python_docker_image: &python_docker_image
  docker:
    - image: python:3.7.3-stretch

commands:
  destroy-environment:
    description: Destroy vpc and eks cloudformation stacks given a workflow ID.    
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
              aws cloudformation delete-stack --stack-name network-stack-${ENV_NAME}
              aws cloudformation delete-stack --stack-name eks-stack-${CIRCLE_WORKFLOW_ID:0:7}

jobs:

    build-test-lint:
      <<: *python_docker_image
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "./app/requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
        - run:
            name: set up python
            command: |
                cd ./app
                make setup
        - run:
            name: install dependencies
            command: |
                cd ./app
                make install
        - save_cache:
            paths:
                - ./.devops
            key: v1-dependencies-{{ checksum "./app/requirements.txt" }}
        - run:
            name: run test
            command: |
                cd ./app
                make test
        - run:
            name: run lint
            command: |
              cd ./app
              source .devops/bin/activate
              make lint
  
    deploy-aws-network:
      <<: *aws_docker_image
      steps:
        - checkout
        - run:
            name: deploy network stack
            command: .circleci/scripts/deploy-network.sh ${ENV_NAME}        
            no_output_timeout: 30m

    deploy-aws-eks:
      <<: *aws_docker_image
      steps:
        - run:
            name: deploy eks cluster
            command: .circleci/scripts/deploy-cluster.sh ${ENV_NAME}
            no_output_timeout: 30m

workflows:
  deploy-application:
    jobs:
      - build-test-lint
      - deploy-infrastructure-network:
          requires: [build-test-lint]
          filters:
            branches:
              only: [main]
      - create-aws-eks:
          requires: [deploy-infrastructure-network]
          filters:
            branches:
              only: [main]
  