version: 2.1

jobs:

    build-test-lint:
        # Use the same Docker base as the project
        - image: python:3.7.3-stretch

      working_directory: ~/repo

      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "requirements.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run:
            name: set up python
            command: make setup

        - run:
            name: install dependencies
            command: make install

        - save_cache:
            paths:
                - ./.devops
            key: v1-dependencies-{{ checksum "requirements.txt" }}

        - run:
            name: run lint
            command: |
              source .devops/bin/activate
              make lint 

workflows:
  build-test-lint:
    jobs:
      - build-test-lint
